---
# tasks file for linux-system-roles.tang

- name: Ensure tang is installed
  package:
    name: tang
    state: present


- name: Ensure tang is enabled and started
  when: state != "stopped"
  systemd:
    name: tangd.socket
    enabled: yes
    masked: no
    state: started


- name: Ensure tang is enabled and stopped
  when: state == "stopped"
  systemd:
    name: tangd.socket
    enabled: yes
    masked: no
    state: stopped


- name: Ensure we have keys
  tang:
    state: keys-created
    keygen: "{{ tang_keygen }}"
    keydir: "{{ tang_keydir }}"


- name: Ensure we create new keys
  when: create_new_keys
  tang:
    state: keys-created
    force: yes
    keygen: "{{ tang_keygen }}"
    keydir: "{{ tang_keydir }}"


- name: Ensure keys are rotated
  when: rotate_keys
  tang:
    state: keys-rotated
    keydir: "{{ tang_keydir }}"
# vim:set ts=2 sw=2 et:
