# SPDX-License-Identifier: MIT
---
- name: Ensure NBDE server is deployed and returns its keys to management node
  hosts: nbde_servers_test
  become: true

  roles:
    - role: nbde_server
      nbde_server_fetch_keys: yes
      nbde_server_keys_dir: "keys-to-deploy"

# vim:set ts=2 sw=2 et:
