# SPDX-License-Identifier: MIT
---
- name: Ensure NBDE server creates new keys and deploy them
  hosts: nbde_servers_test
  become: true


  roles:
    - role: nbde_server
      nbde_server_create_new_keys: yes
      nbde_server_deploy_keys: yes
      nbde_server_keys_dir: "keys-to-deploy"

# vim:set ts=2 sw=2 et:
